batch_size: 32
epochs: 1
rounds: 2
num_clients: 100
num_mal_clients: 1
attack_epochs: 10
mal_boost: 1
wait_for_clients: true
dataset_name: 'fashion-mnist' # 'cifar10' || 'fashion-mnist' || 'mnist'
net_name: "FashionMNISTCNN" # "Cifar10CNN" || "MNISTCNN" || "FashionMNISTCNN"
# Use cuda is available; setting to false will force CPU
defense: 'WBC'
pert_strength: 0.1
cuda: false
experiment_prefix: 'experiment_sample'
wandb_name: 'with defense WBC'
offload_stategy: deadline
output_location: 'output'
tensor_board_active: true
clients_per_round: 3
single_machine: true
use_wandb: false
sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
#sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
sampler_args:
  - 0.07     # label limit || q probability || alpha || unused
  - 42    # random seed || random seed || random seed || unused