batch_size: 32
epochs: 1
rounds: 10
num_clients: 2
wait_for_clients: true
data_set_name: 'mnist'
net_name: "MNISTCNN"
# Use cuda is available; setting to false will force CPU

cuda: false
experiment_prefix: 'experiment_sample'
offload_stategy: deadline
output_location: 'output'
tensor_board_active: true
clients_per_round: 1
single_machine: true
sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
#sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
sampler_args:
  - 0.07     # label limit || q probability || alpha || unused
  - 42    # random seed || random seed || random seed || unused
aggregation_method: ""
